version: 0.0
os: linux
files:
 - source: /src
   destination: /home/ubuntu/python-flask-service
 - source: requirements.txt
   destination: /home/ubuntu/python-flask-service
permissions:
  - object: /home/ubuntu/python-flask-service/application.py
    owner: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/python-flask-service/flaskrun.py
    owner: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/python-flask-service/requirements.txt
    owner: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/python-flask-service/supervisor.conf
    owner: ubuntu
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: root
