#!/bin/bash
sudo apt update
sudo apt -y upgrade
python3 -V
sudo apt install -y python3-pip
pip3 install package_name
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
sudo apt install -y python3-venv
mkdir environments
cd environments
python3 -m venv my_env
ls my_env
source my_env/bin/activate
vi hello.py
python hello.py


pip install -r requirements.txt
pip install supervisor
